MODEL_NAME = "large-v3-turbo"
STT_BACKEND_TYPE = "whisper_faster"
DEVICE = "cuda"
COMPUTE_TYPE = "float16"
LANGUAGE = "en"

INCLUDE_TIME_DATA = True

SAMPLE_RATE = 16000
CHUNK_MS = 500
WINDOW_SEC = 5.0
STEP_SEC = 5.0

OUT_TXT = "logs/output.txt"

LABEL_THRESHOLD = 0.6

CHAMP_THRESHOLD = 0.9
RETRY_MAX = 1
RETRY_DELAY = 0.3
MIN_CLS_PROB = 0.55
MIN_OCR_SCORE = 0.65
CHAMP_RETRY_WAIT = 5.0

DEFAULT_HOTWORDS_TXT = r"C:\Capston\default_hotwords.txt"
USE_SCREEN_OCR_HOTWORDS = True
SCREEN_OCR_INCLUDE_SKILLS = False